### ISSUE TITLE
Adding metadata under blastula_email output_format

### ISSUE THREAD

**Issue by jooyoungseo** [rich-iannone/blastula#219]
Currently, we have the following workflow in order to send a message:

1. Making an email message object;
2. Sending the object with required metadata added via `blastula::smtp_send`.

Could we have a way to directly add the metadata (e.g., from, to, credentials, etc.) under the `blastula::blastula_email` output_format so that we can draft all-in-one in an Rmd file, and send it right off the bat via `blastula::render_email()`?

In sum, the following includes suggested YAML:

``` yaml
---
output:
  blastula::blastula_email:
    from: ...
    to: ...
    subject: ...
    credentials: # Needed when the global key is not available.
knit: "blastula::render_email"
---
```
